# Generated by Django 3.2.7 on 2021-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Grupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_grupp_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Bolalar yoshi',
                'verbose_name_plural': 'Bolalar yoshi',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=50)),
                ('telegram_url', models.URLField(blank=True)),
                ('imstagram_url', models.URLField(blank=True)),
                ('likedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='Teachers/%Y/%m/')),
            ],
            options={
                'verbose_name': "O'qituvchilar",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Class_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('number_of_classes', models.IntegerField(default=0)),
                ('class_price', models.BigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Class/%Y/%m/')),
                ('age_grupp', models.ManyToManyField(to='website.Age_Grupp')),
            ],
            options={
                'verbose_name': 'Class_blog',
                'verbose_name_plural': 'Class_blog',
            },
        ),
    ]
