# Generated by Django 3.2.7 on 2021-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallarey'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallarey',
            name='url',
            field=models.URLField(default='addurl'),
            preserve_default=False,
        ),
    ]
